### ISSUE TITLE
OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by aboodvan** [lec0dex/FGVC#2]
Hey,

I have tried to run this using tennis data but I'm getting this error "OverflowError: Python int too large to convert to C long"
I'd apprecaite it if there's a workaround or fix.

Thanks.

Specs:
AMD 3950x
64gb DDR4
2080 Super 8gb
Windows 10
Anaconda

Log:
(FGVC) E:\AI\FGVC-master>python 1-create-flow.py        --mode video_extrapolation        --path ./data/tennis        --outroot ./result/tennis_extrapolation        --H_scale 2        --W_scale 2
C:\Users\*****\anaconda3\envs\FGVC\lib\site-packages\ray\autoscaler\_private\cli_logger.py:57: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  warnings.warn(
2021-08-06 11:59:48,630 INFO services.py:1245 -- View the Ray dashboard at http://127.0.0.1:8265
Importing frames:   0%|                                                                         | 0/70 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "1-create-flow.py", line 487, in <module>
    main(args)
  File "1-create-flow.py", line 452, in main
    video_completion_seamless(args)
  File "1-create-flow.py", line 398, in video_completion_seamless
    save_checksum(zdata, zvideo[..., frame], 0, frame)
  File "1-create-flow.py", line 114, in save_checksum
    dataset['checksum'][process_num, frame] = crc32(np_arr.tobytes()) if np_arr is not None else 0
  File "C:\Users\*****\anaconda3\envs\FGVC\lib\site-packages\zarr\core.py", line 1213, in __setitem__
    self.set_basic_selection(selection, value, fields=fields)
  File "C:\Users\*****\anaconda3\envs\FGVC\lib\site-packages\zarr\core.py", line 1308, in set_basic_selection
    return self._set_basic_selection_nd(selection, value, fields=fields)
  File "C:\Users\*****\anaconda3\envs\FGVC\lib\site-packages\zarr\core.py", line 1599, in _set_basic_selection_nd
    self._set_selection(indexer, value, fields=fields)
  File "C:\Users\*****\anaconda3\envs\FGVC\lib\site-packages\zarr\core.py", line 1651, in _set_selection
    self._chunk_setitem(chunk_coords, chunk_selection, chunk_value, fields=fields)
  File "C:\Users\*****\anaconda3\envs\FGVC\lib\site-packages\zarr\core.py", line 1888, in _chunk_setitem
    self._chunk_setitem_nosync(chunk_coords, chunk_selection, value,
  File "C:\Users\*****\anaconda3\envs\FGVC\lib\site-packages\zarr\core.py", line 1893, in _chunk_setitem_nosync
    cdata = self._process_for_setitem(ckey, chunk_selection, value, fields=fields)
  File "C:\Users\*****\anaconda3\envs\FGVC\lib\site-packages\zarr\core.py", line 1949, in _process_for_setitem
    chunk[chunk_selection] = value
OverflowError: Python int too large to convert to C long

(FGVC) E:\AI\FGVC-master>

**Comment by lec0dex** [comment]
The code was not tested on Windows. Please try on Linux, preferably on Ubuntu 20.04 LTS

**Comment by MyaaMyaa** [comment]
Yes same here. Integer has to be converted into a float or something to make it work on Windows. That's what I googled and found out. I don't know how much trouble it is for the author. Maybe @lec0dex can look into it or at least tell us how much trouble it is. I would really apprecaite this working on Windows.  FGVC is amazing but you can't make it run 1080p even on top cards with lots of VRAM
